schema {
  query: Query
  mutation: Mutation
}

type Mutation {
  addTask(description: String): Task
  finalizeTask(task: ID!): String
}

type Operation {
  assetId: String
  createdAt: String
  metadata: String
  operation: ID
  state: String
}

type Query {
  getFilesNamesbyTask(task: ID): [String]
  getOperation(operation: ID!): Operation
  getTask(task: ID!): Task
  getUploadUrl(fileName: String!, task: ID!): String
  listTask(nextToken: String): TaskList
}

type Task {
  createdAt: AWSDateTime
  description: String
  files: [String]
  state: String
  task: ID!
}

type TaskList {
  nextToken: String
  tasks: [Task]
}
