/**
 * App events manager.
 * Requires an AppEventsRecord type, generated by the application, which defines the events schema.
 *
 * @example ```typescript
 * // Example of an AppEventsRecord type definition:
 * export type AppEventsRecord = {
 *    "page-loaded": [string];
 *    "new-user": [{username:string, level:number}];
 *    "ping": [string];
 * };
 * const appEvents = new AppEvents<AppEventsRecord>()
 * ```
 *
 * @example
 * ```typescript
 * import {appEvents} from "./appEvents" // Import the abstract class
 *
 * appEvents.pub("page-loaded", location.href) // Publish an event
 * appEvents.sub("page-loaded", ({data})=>console.log(data)) // Subscribe to an event
 * ```
 */
export class AppEvents<
  /** Mapping of events -> callback data */
  InputType extends EventsMap<BaseEvents>
> {
  constructor(
    emitter: Window | BroadcastChannel | MessageEventSource = window
  ) {
    this.#emitter = emitter;
    this.#listener =
      emitter instanceof BroadcastChannel
        ? new BroadcastChannel(emitter.name)
        : window;
  }

  #randHex = () => ((Math.random() * 16) | 0).toString(16);

  #createID = () => "########".replace(/[#]/g, this.#randHex);
  /** Unique identifier representing a specific instance of the AppEvents class */
  instanceID = this.#createID();
  #emitter;
  #listener;
  /** Contains a record of every subscriber */
  #subscriptions: Record<string, Listener> = {};

  /**
   * Adds a new subscriber
   * @returns The generated ID of the subscriber, can be used to remove the subscription
   */
  #addSubscription = (fn: Listener, id: string) => {
    this.#subscriptions[id] = fn;
    return id;
  };

  /** Removes a subscriber using its generated ID. */
  #removeSubscription = (id: string) => {
    this.#listener.removeEventListener(
      "message",
      this.#subscriptions[id] as EventListenerOrEventListenerObject
    );
    delete this.#subscriptions[id];
  };

  /**
   * Publish an event.
   * @param type The event type, as listed in AppEventRecord.
   * @param data The data corresponding to the event type
   * @example ```typescript
   * AppEvents.pub("page-loaded", location.href)
   * ```
   */
  pub = <T extends AppEventType<InputType>>(
    type: T,
    ..._data: InputType[T]
  ) => {
    const [data] = _data;
    if (this.#emitter instanceof BroadcastChannel) {
      this.#emitter.postMessage({ type, data, id: this.instanceID });
    } else {
      this.#emitter.postMessage(
        { type, data, id: this.instanceID },
        { targetOrigin: "*" }
      );
    }
  };

  /**
   * Publishes an event to an external EventSource.
   * @param source The event type, as listed in AppEventRecord.
   * @param type The event type, as listed in AppEventRecord.
   * @param _data The data corresponding to the event type
   * @example ```typescript
   * AppEvents.pub("page-loaded", location.href)
   * ```
   */
  to = <T extends AppEventType<InputType>>(
    source: MessageEventSource | null,
    type: T,
    ..._data: InputType[T]
  ) => {
    const [data] = _data;
    if (!source)
      return console.warn(
        "Tried to send a message to a null MessageEventSource."
      );
    if (source instanceof BroadcastChannel) {
      source.postMessage({ type, data, id: this.instanceID });
    } else {
      source.postMessage(
        { type, data, id: this.instanceID },
        { targetOrigin: "*" }
      );
    }
  };

  /**
   * Subscribe to an event.
   * @returns Subscription ID - used to unsubscribe
   *
   * @example ```typescript
   * // Single event subscription
   * AppEvents.sub("page-loaded", ({data})=>{
   *  const [location] = data;
   *  console.log(location)
   * })
   *
   * // Multiple events subscription
   * AppEvents.sub(["page-loaded", "new-user"], ({type, data, id}, event)=>{
   *  if(type === "page-loaded") {
   *    const location = data;
   *    console.log(location)
   *  } else {
   *    const {timestamp, user} = data;
   *    console.log(user.username, timestamp)
   *  }
   * })
   * ```
   */
  sub = <T extends AppEventType<InputType>>(
    type: T | T[],
    handler: AppEventsHandler<InputType, T>
  ) => {
    const id = this.#createID();
    const handlerWrapper = (
      e: MessageEvent<AppMessages<InputType>[T] & { id: string }>
    ) => {
      const isArray = type instanceof Array;
      if (isArray && !type.includes(e.data.type)) return;
      if (!isArray && type !== e.data.type) return;
      handler(e.data, e);
    };
    this.#listener.addEventListener("message", handlerWrapper as EventListener);
    return this.#addSubscription(handlerWrapper, id);
  };
  /** Just like the `sub` methods, but just once. */
  once = <T extends AppEventType<InputType>>(
    type: T | T[],
    handler: AppEventsHandler<InputType, T>
  ) => {
    const id = this.#createID();
    const handlerWrapper = (
      e: MessageEvent<AppMessages<InputType>[T] & { id: string }>
    ) => {
      const isArray = type instanceof Array;
      if (isArray && !type.includes(e.data.type)) return;
      if (!isArray && type !== e.data.type) return;
      handler(e.data, e);
      this.unsub(id);
    };
    this.#listener.addEventListener("message", handlerWrapper as EventListener);
    return this.#addSubscription(handlerWrapper, id);
  };
  /**
   * Waits for an event, if it doesn't happen throws an error.
   * @param type The event to wait for
   * @param timeout Time to wait for the event before throwing an error
   * @returns The parameters of the event listener
   */
  async = <T extends AppEventType<InputType>>(
    type: T | T[],
    timeout: number = 5000
  ) => {
    return new Promise<Parameters<AppEventsHandler<InputType, T>>>(
      (resolve, reject) => {
        // Once the event triggers, clears the timeout and resolves the promise
        const timeoutID: { value?: NodeJS.Timeout } = {
          value: undefined,
        };
        const subscriberID = this.once(type, (...args) => {
          clearTimeout(timeoutID.value);
          return resolve(args);
        });
        // If the timeout time expired rejects the promise and unsubs the subscriber
        timeoutID.value = setTimeout(() => {
          this.unsub(subscriberID);
          reject(
            new Error(
              `Timeout: async event ${String(
                type
              )} has been aborted. It is taking longer than the allowed timeout time(${timeout} ms).`
            )
          );
        }, timeout);
      }
    );
  };

  /**
   * Unsubscribes a subscriber.
   * Always unsubscribe from events you don't need anymore to avoid lingering listeners.
   * @param id The ID generated at subscribe-time
   */
  unsub = (id: string) => {
    this.#removeSubscription(id);
  };
}

/**
 * Despite the values being arrays, they must hold either 1 or 0 elements. Further elements will be ignored.
 * @example
 *  export type AppEventsRecord = {
 *    "page-loaded": [string];
 *    "new-user": [{username:string, level:number}];
 *    "ping": [string];
 * };
 */
type BaseEvents = Record<string, [...any] | []>;
type EventsMap<T extends BaseEvents> = {
  [Properties in keyof T]: T[Properties];
};
type AppEventType<T extends BaseEvents> = keyof EventsMap<T>;
type Listener = (this: Window, ev: MessageEvent<any>) => any;

export type AppMessages<T extends BaseEvents> = {
  [Property in keyof EventsMap<T>]: {
    type: Property;
    data: EventsMap<T>[Property][0];
  };
};

/** Callback to provide one of the subscribe events of the AppEvents class.  */
export type AppEventsHandler<
  T extends BaseEvents,
  K extends AppEventType<T>
> = (
  message: AppMessages<T>[K] & { id: string },
  event: MessageEvent<AppMessages<T>[K]>
) => void;
